const uselessCorrections = {
  "google": "Go Ogle",
  "laptop": "lap dog",
  "keyboard": "key bored",
  "hello": "hullo",
  "password": "pa$$w0rd",
  "internet": "InterNOT",
  "friend": "fiend",
  "success": "succ mess",
  "cat": "dog",
  "important": "not important",
  "phone": "phony",
  "computer": "compooter",
  "mouse": "moose",
  "monitor": "moniterror",
  "printer": "print error",
  "coffee": "my life",
  "meeting": "meating",
  "project": "procrastination",
  "deadline": "dead line",
  "work": "wurk",
  "boss": "bo$$",
  "house": "hoose",
  "car": "cart",
  "window": "wind-oh",
  "light": "lite",
  "dark": "dank",
  "water": "wet stuff",
  "food": "yum",
  "chair": "sit thing",
  "table": "flat top",
  "shoes": "footskins",
  "hat": "head lid",
  "shirt": "torso tarp",
  "pants": "leg sleeves",
  "cold": "brrr",
  "hot": "ouch",
  "fast": "zoom",
  "slow": "snail mode",
  "funny": "lolz",
  "boring": "snore fest",
  "happy": "yay",
  "sad": "boo hoo",
  "angry": "grr",
  "tired": "zzz",
  "morning": "mourn-thing",
  "night": "dark time",
  "bed": "dream zone",
  "sleep": "nap mode",
  "wake up": "error",
  "bathroom": "throne room",
  "kitchen": "food lab",
  "living room": "lazy zone",
  "book": "boring box",
  "movie": "lazy book",
  "game": "distraction device",
  "music": "ear candy",
  "song": "noise art",
  "dance": "wiggle time",
  "run": "fast walk",
  "walk": "leg shuffle",
  "jump": "floor escape",
  "ride": "lazy travel",
  "drive": "steer thing",
  "bike": "pedal horse",
  "bus": "people box",
  "train": "chug chug",
  "airplane": "sky boat",
  "boat": "water car",
  "subway": "underground snake",
  "road": "ground line",
  "highway": "speed zone",
  "street": "walk way",
  "sidewalk": "no car zone",
  "park": "grass place",
  "school": "homework jail",
  "teacher": "knowledge overlord",
  "student": "learning minion",
  "homework": "pain work",
  "exam": "stress test",
  "test": "brain torture",
  "math": "number sorcery",
  "science": "mad experiments",
  "history": "old gossip",
  "language": "word spaghetti",
  "art": "messy creativity",
  "paint": "color splash",
  "draw": "pen dance",
  "pencil": "wood scribbler",
  "pen": "ink stick",
  "paper": "tree corpse",
  "notebook": "idea trap",
  "calendar": "date jail",
  "clock": "time prison",
  "watch": "wrist clock",
  "alarm": "screaming clock",
  "time": "what even is it?",
  "day": "sun time",
  "week": "7-day struggle",
  "month": "bill cycle",
  "year": "age counter",
  "century": "forever",
  "decade": "10 years of mistakes",
  "minute": "tiny hour",
  "second": "tiny minute",
  "weather": "sky mood",
  "rain": "cloud tears",
  "snow": "sky dandruff",
  "sun": "fire ball",
  "moon": "night lamp",
  "star": "tiny sun",
  "cloud": "sky fluff",
  "storm": "angry weather",
  "wind": "air push",
  "hurricane": "sky tantrum",
  "tornado": "air blender",
  "earthquake": "ground shake",
  "fire": "ouch hot",
  "ice": "ouch cold",
  "money": "paper power",
  "bank": "money jail",
  "credit card": "debt rectangle",
  "cash": "paper trade",
  "rich": "loaded",
  "poor": "broke life",
  "shopping": "wallet attack",
  "store": "spend zone",
  "market": "trade circus",
  "supermarket": "food jungle",
  "mall": "money trap",
  "restaurant": "food palace",
  "fast food": "grease heaven",
  "dessert": "sugar rush",
  "breakfast": "morning fuel",
  "lunch": "midday munch",
  "dinner": "evening feast",
  "snack": "tiny feast",
  "candy": "sugar bomb",
  "chocolate": "mood fixer",
  "cookie": "sweet circle",
  "cake": "celebration brick",
  "pizza": "cheese circle",
  "burger": "meat sandwich",
  "fries": "potato sticks",
  "soda": "fizzy sugar",
  "coffee": "survival juice",
  "tea": "leaf water",
  "milk": "cow juice",
  "juice": "fruit liquid",
  "water bottle": "hydration vessel",
  "exercise": "sweat torture",
  "gym": "muscle farm",
  "sports": "sweaty games",
  "soccer": "kick ball",
  "basketball": "hoop throw",
  "tennis": "racket smack",
  "volleyball": "hand soccer",
  "golf": "rich person walk",
  "hockey": "ice chaos",
  "football": "hand egg",
  "baseball": "bat swing",
  "boxing": "punch fun",
  "swimming": "water survival",
  "running": "sweaty feet",
  "hiking": "nature walk",
  "camping": "outdoor suffering",
  "fishing": "fish trickery",
  "hunting": "animal hide and seek",
  "duck": "Quackbird",
};

// Function to replace words while typing
function autocorrectText(event) {
  let target = event.target;

  if (target.tagName === "INPUT" || target.tagName === "TEXTAREA") {
    // Cancel any previously scheduled autocorrection
    if (target.autocorrectTimeout) {
      clearTimeout(target.autocorrectTimeout);
      target.autocorrectTimeout = null;
    }

    // Only schedule if the input ends with a space (word completed)
    if (target.tagName === "INPUT" || target.tagName === "TEXTAREA") {
      let words = target.value.split(" ");
      let lastWord = words[words.length - 1];

      if (uselessCorrections[lastWord]) {
        console.log(lastWord);

        words[words.length - 1] = uselessCorrections[lastWord.toLowerCase()];
        target.value = words.join(" ");
      }
    }
  }

}

// Attach event listeners to all text fields
document.addEventListener("input", autocorrectText);
